export const COFFEE_LIST_OK = 'COFFEE_LIST_OK'; 
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'